language: cpp
sudo: false

compiler:
  - gcc
  - clang

env:
  global:
    - SASS_LIBSASS_PATH=$TRAVIS_BUILD_DIR/libsass
    - SASS_SPEC_PATH=$TRAVIS_BUILD_DIR/sass-spec
  matrix:
    - AUTOTOOLS=no BUILD=shared
    - AUTOTOOLS=no BUILD=static
    - AUTOTOOLS=yes BUILD=shared
    - AUTOTOOLS=yes BUILD=static

script:
  - ./script/ci-build-libsass

after_success:
  - ./bin/sassc -v
  - ldd ./bin/sassc
