language: cpp
sudo: false

compiler:
  - gcc
  - clang

env:
  - AUTOTOOLS=yes
  - AUTOTOOLS=no
  - BUILD=shared
  - BUILD=static

before_install:
  - gem install sass
  - git clone https://github.com/sass/libsass.git
  - cd libsass && git submodule init && git submodule update && cd ..
  - export SASS_LIBSASS_PATH=$TRAVIS_BUILD_DIR/libsass

script:
  - ./script/ci-build-libsass

after_success:
  - ./bin/sassc -v
  - ldd ./bin/sassc
